#!/usr/bin/env python3

import json
import os

from hdwallet import HDWallet
from hdwallet_boosted import BoostedHDWallet

# Test Values
base_path: str = os.path.dirname(__file__)
file_path: str = os.path.abspath(os.path.join(base_path, "./values.json"))
values = open(file_path, "r", encoding="utf-8")
_: dict = json.loads(values.read())
values.close()


def _generate_xpublic_key():
    hdwallet: HDWallet = HDWallet(
        symbol=_["bitcoin"]["mainnet"]["symbol"]
    )
    
    hdwallet.from_mnemonic(
        mnemonic=_["bitcoin"]["mainnet"]["mnemonic"],
        passphrase=_["bitcoin"]["mainnet"]["passphrase"],
        language=_["bitcoin"]["mainnet"]["language"]
    )
    hdwallet.clean_derivation()
    hdwallet.from_path(path="m/44'/0/0'/0")
    return hdwallet.xpublic_key()


def _create_wallet_instance(cls, xpublic_key):
    wallet = cls(symbol=_["bitcoin"]["mainnet"]["symbol"])
    wallet.from_xpublic_key(xpublic_key)
    wallet.clean_derivation()
    return wallet


def _get_address_for_index(wallet_instance, index):
    wallet_instance.clean_derivation()
    wallet_instance.from_index(index)
    return wallet_instance.p2pkh_address()


def test_address_correct():
    """
    Ensure address generated by original code is the same after optimization.
    """
    xpublic_key = _generate_xpublic_key()
    orig_wallet = _create_wallet_instance(HDWallet, xpublic_key)
    boosted_wallet = _create_wallet_instance(BoostedHDWallet, xpublic_key)

    for index in range(10):
        orig_address = _get_address_for_index(orig_wallet, index)
        boosted_address = _get_address_for_index(boosted_wallet, index)

        assert orig_address == boosted_address
